import { SectionsNames } from "@/enums/sectionsNames";

export const sectionsOrder = [
  SectionsNames.MarkdownLanguages,
  SectionsNames.ProgrammingLanguages,
  SectionsNames.JavascriptLibraries,
  SectionsNames.MobileFrameworks,
  SectionsNames.PhpFrameworks,
  SectionsNames.JavaFrameworks,
  SectionsNames.ReactNativeLibraries,
  SectionsNames.StateManagementLibraries,
  SectionsNames.FetchingLibraries,
  SectionsNames.FormLibraries,
  SectionsNames.UiLibraries,
  SectionsNames.DataVisualization,
  SectionsNames.AnimationsLibraries,
  SectionsNames.TestingFrameworksAndTools,
  SectionsNames.Internationalization,
  SectionsNames.Maps,
  SectionsNames.BackendTechnologies,
  SectionsNames.Cloud,
  SectionsNames.Databases,
  SectionsNames.Cms,
  SectionsNames.PaymentTools,
  SectionsNames.WebServices,
  SectionsNames.AuthorizationTools,
  SectionsNames.Containerization,
  SectionsNames.Web3,
  SectionsNames.Analytics,
  SectionsNames.Security,
  SectionsNames.CiCd,
  SectionsNames.SpeechRecognition,
  SectionsNames.Virtualization,
  SectionsNames.Documentation,
  SectionsNames.LoggingTools,
  SectionsNames.PerformanceMonitoringTools,
  SectionsNames.ModuleBundlers,
  SectionsNames.GraphicEditors,
  SectionsNames.VersionControlSystems,
  SectionsNames.AITools,
  SectionsNames.NotFound,
];

// Broad categories used for the "Hays" grouping mode - same buckets as the summary field
export const broadSectionsOrder = [
  SectionsNames.ProgrammingLanguages,
  SectionsNames.Frontend,
  SectionsNames.BackendTechnologies,
  SectionsNames.JavaFrameworks,
  SectionsNames.Containerization,
  SectionsNames.CiCd,
  SectionsNames.Cloud,
  SectionsNames.Databases,
  SectionsNames.VersionControlSystems,
  SectionsNames.AITools,
];
